### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by joshaber**
Use Travis for CI and fix the tests (hopefully :pray:).

### CODE REVIEW

**Comment by joshaber** [comment]
Huh, so the failure is because it can't sign the test app. I guess we'll have to add the cert to the repo? Or something?

**Comment by mdiep** [comment]
Does it need to be codesigned?

**Comment by joshaber** [comment]
IIRC part of the testing is signature verification so without that we're cobbling the tests.

**Comment by joshaber** [comment]
:metal: It's at least building and running tests now.

**Comment by joshaber** [comment]
Well, all the tests are passing except that some will randomly fail:

>"The application “TestApplication” could not be launched because a miscellaneous error occurred (OSStatus -10810)."

I haven't seen this locally so I kinda think it's a Travis-ism. I'll keep poking around, but if anyone has any ideas throw the out there :pray:

**Comment by joshaber** [comment]
Well, I :doughnut: know what's going on.

Unless anyone else has ideas, my current plan is to detect when we're running tests on Travis and disable those tests :cry:

**Comment by joshaber** [comment]
This is ready, but

**Comment by mdiep** [comment]
97558-arrested-development-taste-my-sad-michael

**Pull request merged**
