### PR TITLE
[WIP] Try to unquarantine the host app before checking for updates.

### LINKED ISSUE #182: Gatekeeper Path Randomization makes life hard
1. Use macOS Sierra.
2. Download an app to `~/Downloads`.
3. Launch app.
4. Update found.
5. Prompted to auth update helper (??)
6. Update can't be installed.

This is because of Gatekeeper's path randomization, new in Sierra. Once you do something that deactivates path randomization (e.g., move the app), updates are fine.

This sucks. It's not terribly clear how we can deal with it. Try to detect it and tell users? Maybe we can explicitly de-quarantine the running app from ShipIt?

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #182

### CODE REVIEW

**Comment by joshaber** [comment]
>I'm surprised an app is allowed to self remove the quarantine but though, that would appear to defeat the protection aspect too

Yeah I'm curious to see if this actually works once I figure out how to test it.

**Comment by keithduncan** [comment]
> I've confirmed that removing com.apple.quarantine from the app fixes this

Ah I misinterpreted this as you having tested it. Right on, I suspect this will in fact not work then :wink:

**Comment by joshaber** [comment]
Yeah, I mean, thinking about this, surely `NSRunningApplication.currentApplication.bundleURL` would be the randomized path, in which case `removexattr` on it is just lulz.

**Comment by keithduncan** [comment]
> Yeah, I mean, thinking about this, surely NSRunningApplication.currentApplication.bundleURL would be the randomized path, in which case removexattr on it is just a joke.

True that, does path randomisation kick in even when you’re sandboxed?

/cc @paulcbetts for details on the magic sandbox update entitlement

**Comment by joshaber** [comment]
Superseded by #186

**Pull request closed without merging**
